<%@ page language="java" contentType="text/xml; charset=UTF-8"
    pageEncoding="UTF-8"%>
<personList>
	<person>
		<name>홍길동</name>
		<gender>남자</gender>
		<age>28</age>
	</person>
	<person>
		<name>성춘향</name>
		<gender>여자</gender>
		<age>29</age>
	</person>
	<person>
		<name>이몽룡</name>
		<gender>남자</gender>
		<age>27</age>
	</person>
</personList>